export {default as adminAuthRoute} from './auth'
export {default as brandRoute} from './brands'
export {default as categoryRoute} from './category'
export {default as userRoute} from './users'
export {default as productRoute} from './product'