export {default as authRoute} from './auth'
export {default as landingRoute} from './landingPage'
export {default as productRoute} from './product'
export {default as categoryRoute} from './category'
export {default as orderRoute} from './order'
export {default as addressRoute} from './address'
export {default as wishRoute} from './wish'